services:
  - type: web
    name: afrishop-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOW_ORIGIN
        sync: false
      - key: JWT_PASSPHRASE
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_PUBLIC_KEY
        sync: false
