# En production, l'entrypoint Docker décode les env vars base64
# et écrit les fichiers PEM dans config/jwt/ au démarrage du conteneur
lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
